import { HashMap } from "./hashmap.js";

const test = new HashMap()
test.set('apple', 'red')
test.set('banana', 'yellow')
test.set('carrot', 'orange')
test.set('dog', 'brown')
test.set('elephant', 'gray')
test.set('frog', 'green')
test.set('grape', 'purple')
test.set('hat', 'black')
test.set('ice cream', 'white')
test.set('jacket', 'blue')
test.set('kite', 'pink')
test.set('lion', 'golden')

test.set('lion', 'golden-like')
test.set('apple', 'redish')
test.set('banana', 'yellowish')

test.set('moon', 'silver')

console.log(test)
console.log(test.get('apple'))
console.log(test.get('lion'))
console.log(test.get('banana'))
console.log(test.get('lion'))

console.log(test.length())
console.log(test.values())
console.log(test.entries())
console.log(test.keys())
console.log(test.has("fruit"))
console.log(test.has("moon"))
console.log(test.remove("moon"))
console.log(test.remove("apple"))
console.log(test.length())
console.log(test.has("moon"))
test.set('moon', 'silver')
console.log(test.length())
console.log(test.values())
console.log(test.entries())
console.log(test.keys())
console.log(test.get('orange'))